# -*- coding: utf-8 -*-
"""HabitTracker_V2.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3QrtV1k6EmenghW4whJBOvpHbw1_vaD
"""

import os
import json
import datetime

FILE_NAME = "habits.json"
today = str(datetime.date.today())

# ==========================================
# Phase 1: INITIAL SETUP & MEMORY LOAD
# ==========================================
if os.path.exists(FILE_NAME):
    with open(FILE_NAME, "r") as file:
        my_habits = json.load(file)
    print("Welcome back! Database loaded successfully.")
else:
    print("Welcome to your new Multi-Habit Tracker!")
    first_habit = input("What is the first habit you want to track? ").lower()
    my_habits = {first_habit: []}
    with open(FILE_NAME, "w") as file:
        json.dump(my_habits, file)
    print(f"\nAwesome! '{first_habit}' has been added to your database.")

# ==========================================
# Phase 2: THE INFINITE LOOP (Main Menu)
# ==========================================
while True:
    print("\n=== MAIN MENU ===")
    print("Here are your current habits:")
    for habit in my_habits.keys():
        print(f"- {habit}")

    print("\nWhat would you like to do?")
    print("1. Log today's scores")
    print("2. Add a new habit")
    print("3. Remove a habit")
    print("4. Use the Time Machine (Edit past scores)")
    print("5. Quit and view report")

    menu_choice = input("Type 1, 2, 3, 4, or 5: ")

    if menu_choice == "2":
        new_habit = input("\nWhat new habit do you want to track? ").lower()
        my_habits[new_habit] = []
        with open(FILE_NAME, "w") as file:
            json.dump(my_habits, file)
        print(f"Great! '{new_habit}' has been added to your list.\n")

    elif menu_choice == "1":
        # --- THE TIME COP UPGRADE ---
        if os.path.exists("last_login.txt"):
            with open("last_login.txt", "r") as file:
                last_login = file.read().strip()

            # Make sure the file isn't empty before doing Date Math
            if last_login != "":
                last_date = datetime.datetime.strptime(last_login, "%Y-%m-%d").date()
                today_date = datetime.date.today()
                days_passed = (today_date - last_date).days

                # If more than 1 day has passed, sound the alarm!
                if days_passed > 1:
                    missed_days = days_passed - 1
                    print(f"\n🚨 TIME COP: You missed {missed_days} day(s)! Auto-filling with 'False'...")

                    for habit in my_habits.keys():
                        for _ in range(missed_days):
                            my_habits[habit].append(False)

                    with open(FILE_NAME, "w") as file:
                        json.dump(my_habits, file)
        else:
            last_login = ""
        # ----------------------------

        # The Trap Door!
        if last_login == today:
            print("\nYou already checked in today! Come back tomorrow. 🛑")
        else:
            print("\n--- Time for your daily check-in! ---")
            for habit in my_habits.keys():
                user_answer = input(f"Did you complete your '{habit}' goal today? (yes/no): ").lower()
                while user_answer not in ["yes", "no"]:
                    print("What? Was that a yes or no?")
                    user_answer = input("Type 'yes' or 'no': ").lower()

                if user_answer == "yes":
                    my_habits[habit].append(True)
                else:
                    my_habits[habit].append(False)

            with open(FILE_NAME, "w") as file:
                json.dump(my_habits, file)
            with open("last_login.txt", "w") as file:
                file.write(today)
            print("\nAll your scores have been saved to the database!")

    elif menu_choice == "3":
        habit_to_delete = input("\nWhich habit do you want to permanently delete? ").lower()
        if habit_to_delete in my_habits:
            del my_habits[habit_to_delete]
            with open(FILE_NAME, "w") as file:
                json.dump(my_habits, file)
            print(f"\nPoof! '{habit_to_delete}' has been deleted from your database.")
        else:
            print(f"\nHmm, I don't see '{habit_to_delete}' in your list. Check your spelling!")

    elif menu_choice == "4":
        # ==========================================
        # 4. THE TIME MACHINE
        # ==========================================
        print("\n⏳ === THE TIME MACHINE === ⏳")
        habit_to_edit = input("Which habit's timeline do you want to alter? ").lower()

        if habit_to_edit in my_habits:
            history = my_habits[habit_to_edit]
            print(f"\nHere is your recorded history for '{habit_to_edit}':")
            print(f"{history}")

            print("\nHow far back do you want to travel?")
            entries_back = input("Type 1 for your most recent entry, 2 for the one before that, etc: ")

            if entries_back.isdigit():
                entries_back = int(entries_back)

                if 0 < entries_back <= len(history):
                    target_index = entries_back * -1

                    new_answer = input("Did you complete this habit on that day? (yes/no): ").lower()
                    if new_answer == "yes":
                        my_habits[habit_to_edit][target_index] = True
                    else:
                        my_habits[habit_to_edit][target_index] = False

                    with open(FILE_NAME, "w") as file:
                        json.dump(my_habits, file)

                    print("\n⚡ Time line successfully altered! ⚡")
                else:
                    print("\nParadox Error: You haven't been tracking this habit for that long!")
            else:
                print("\nError: Please type a valid number.")
        else:
            print(f"\nHmm, I don't see '{habit_to_edit}' in your database.")

    elif menu_choice == "5":
        print("\nExiting the app... Generating final report!")
        break

    else:
        print("\nInvalid input. Please type 1, 2, 3, 4, or 5.")

# ==========================================
# Phase 3: THE HABIT REPORT
# ==========================================
print("\n=== YOUR HABIT REPORT ===")
for habit in my_habits.keys():
    scores = my_habits[habit]
    total_days = len(scores)

    if total_days > 0:
        successful_days = scores.count(True)
        success_rate = (successful_days / total_days) * 100
        print(f"-> {habit}: {round(success_rate)}% success over {total_days} days!")
    else:
        print(f"-> {habit}: No days tracked yet.")